name: Build 3D Models

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Convert models
        run: |
          for zone in */; do
            if [ -d "${zone}src" ]; then
              mkdir -p "${zone}dist"

              for obj in "${zone}"src/*.obj; do
                [ -e "$obj" ] || continue

                name=$(basename "$obj" .obj)

                echo "Procesando ${zone}${name}"

                npx @gltf-transform/cli convert "$obj" "${zone}dist/${name}.glb"
              done
            fi
          done

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if ls */dist/*.glb 1> /dev/null 2>&1; then
            git add */dist/*.glb
            git commit -m "Auto: build GLB models"
            git push
          else
            echo "No GLB files found, skipping commit"
          fi
